/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface OrdQuote {
    'author': string;
    'quote': string;
  }
  interface OrdQuoteAttributes extends StencilHTMLAttributes {
    'author'?: string;
    'quote'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'OrdQuote': Components.OrdQuote;
  }

  interface StencilIntrinsicElements {
    'ord-quote': Components.OrdQuoteAttributes;
  }


  interface HTMLOrdQuoteElement extends Components.OrdQuote, HTMLStencilElement {}
  var HTMLOrdQuoteElement: {
    prototype: HTMLOrdQuoteElement;
    new (): HTMLOrdQuoteElement;
  };

  interface HTMLElementTagNameMap {
    'ord-quote': HTMLOrdQuoteElement
  }

  interface ElementTagNameMap {
    'ord-quote': HTMLOrdQuoteElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
